import { ProductCard } from '@/components/ProductCard/ProductCard';
import { API } from '@/helpers/api';
import { withLayout } from '@/layout/Layout';
import { ProductGridWithPagination } from '@/pageComponents/ProductGridWithPagination/ProductGridWithPagination';
import cls from '@/styles/Home.module.scss';
import { Product } from '@/types';
import { Container } from '@/UI/Container/Container';
import axios from 'axios';
import { GetStaticProps } from 'next';
import Head from 'next/head';

interface HomeProps extends Record<string, unknown> {
    products: Product[];
}

function Home({ products }: HomeProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
            </Head>
            <main>
                <Container>
                    <ProductGridWithPagination products={products} />
                </Container>
            </main>
        </>
    );
}

export default withLayout(Home);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
    const { data: products } = await axios.get<Product[]>(API.product.getProducts);

    return {
        props: {
            products: products,
        },
    };
};
