import { API } from '@/helpers/api';
import cls from '@/styles/Home.module.scss';
import { Product } from '@/types';
import axios from 'axios';
import { GetStaticProps } from 'next';
import Head from 'next/head';

export default function Home({ products }: HomeProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
            </Head>
            <main className={cls.main}>
                {products?.map((product) => (
                    <div key={product.id}>{product.title}</div>
                ))}
            </main>
        </>
    );
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
    const { data: products } = await axios.get<Product[]>(API.product.getProducts);

    return {
        props: {
            products: products,
        },
    };
};

interface HomeProps extends Record<string, unknown> {
    products: Product[];
}
